// =========================================
// ATUL BAKERY — Full Menu Data
// All prices from official menu boards
// =========================================

const menuData = [
  // ============ PASTRIES ($3.99 - $5.99) ============
  { name: "Creamy Vanilla", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Classic vanilla cream pastry" },
  { name: "Ferrero Chocolate", price: "5.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Rich Ferrero-inspired indulgence" },
  { name: "Juicy Pineapple", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Light pineapple cream" },
  { name: "Mango Pastry", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Seasonal mango delight" },
  { name: "Strawberry", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Fresh strawberry cream" },
  { name: "White Forest", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "White chocolate & cherries" },
  { name: "Gulabjamun Cheese", price: "3.99", category: "pastries", tag: "Specialty", icon: "fa-cake-candles", veg: true, desc: "Indian gulabjamun fusion" },
  { name: "Biscoff Cheese", price: "5.99", category: "pastries", tag: "Premium", icon: "fa-cake-candles", veg: true, desc: "Biscoff cheesecake pastry" },
  { name: "Mango Cheese", price: "5.99", category: "pastries", tag: "Premium", icon: "fa-cake-candles", veg: true, desc: "Mango cheesecake pastry" },
  { name: "Black Forest", price: "3.99", category: "pastries", tag: "Classic", icon: "fa-cake-candles", veg: true, desc: "Chocolate & cherry classic" },
  { name: "Blueberry", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Sweet blueberry cream" },
  { name: "Bourbon Chocolate", price: "4.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Decadent bourbon chocolate" },
  { name: "Choco Chips Forest", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Loaded with chocolate chips" },
  { name: "Choco Delight", price: "3.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Pure chocolate joy" },
  { name: "Choco Pie", price: "5.99", category: "pastries", tag: "Premium", icon: "fa-cake-candles", veg: true, desc: "Layered chocolate pie" },
  { name: "Nutty Rose", price: "4.99", category: "pastries", tag: "Specialty", icon: "fa-cake-candles", veg: true, desc: "Rose & nuts blend" },
  { name: "Oreo Crunch", price: "4.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Oreo crunch layers" },
  { name: "Pine Butterscotch", price: "4.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Pineapple butterscotch" },
  { name: "Rasmalai", price: "4.99", category: "pastries", tag: "Specialty", icon: "fa-cake-candles", veg: true, desc: "Indian rasmalai pastry" },
  { name: "Red Velvet", price: "4.99", category: "pastries", tag: "Bestseller", icon: "fa-cake-candles", veg: true, desc: "Iconic red velvet" },
  { name: "Roasted Almond", price: "5.99", category: "pastries", tag: "Premium", icon: "fa-cake-candles", veg: true, desc: "Toasted almond pastry" },
  { name: "Royal Cassata", price: "4.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Tutti-frutti cassata" },
  { name: "Royal Chocolate", price: "4.99", category: "pastries", tag: "Pastry", icon: "fa-cake-candles", veg: true, desc: "Rich royal chocolate" },

  // ============ CAKES (per LB) ============
  { name: "Strawberry Delight", price: "21.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Fresh strawberry layered cake" },
  { name: "Juicy Pineapple Cake", price: "21.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Pineapple cream cake" },
  { name: "Blueberry Cake", price: "21.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Sweet blueberry layers" },
  { name: "Alphonso Cake", price: "21.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Premium alphonso mango" },
  { name: "White Forest Cake", price: "24.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "White chocolate & cherry" },
  { name: "Pine Butterscotch Cake", price: "24.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Pineapple butterscotch" },
  { name: "Pinor Fantasy", price: "24.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Signature fruit fantasy" },
  { name: "Tripple Berry", price: "24.99", unit: "/ lb", category: "cakes", tag: "Fruit", icon: "fa-birthday-cake", veg: true, desc: "Three-berry medley" },
  { name: "Black Forest Cake", price: "21.99", unit: "/ lb", category: "cakes", tag: "India Special", icon: "fa-birthday-cake", veg: true, desc: "Classic chocolate cherry" },
  { name: "Rasbhari Rasmalai", price: "25.99", unit: "/ lb", category: "cakes", tag: "India Special", icon: "fa-birthday-cake", veg: true, desc: "Authentic rasmalai cake" },
  { name: "Royal Cassata Cake", price: "25.99", unit: "/ lb", category: "cakes", tag: "India Special", icon: "fa-birthday-cake", veg: true, desc: "Tutti-frutti cassata" },
  { name: "Nutty Rose Cake", price: "24.99", unit: "/ lb", category: "cakes", tag: "India Special", icon: "fa-birthday-cake", veg: true, desc: "Rose & nuts cake" },
  { name: "Choco Delight", price: "21.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Chocolate cream cake" },
  { name: "Choco Latte", price: "21.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Coffee-chocolate fusion" },
  { name: "Choco Chip Forest", price: "24.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Forest with chocolate chips" },
  { name: "Choco Pie Cake", price: "24.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Pie-style chocolate cake" },
  { name: "Bourbon Chocolate", price: "25.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Bourbon-style chocolate" },
  { name: "Oreo Crunch Cake", price: "25.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Loaded with Oreo" },
  { name: "Royal Chocolate", price: "26.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Royal chocolate experience" },
  { name: "Ferrero Rocher Cake", price: "26.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Inspired by Ferrero" },
  { name: "Roasted Almond Cake", price: "27.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Premium roasted almond" },
  { name: "Kitkat Crunch", price: "34.99", unit: "/ lb", category: "cakes", tag: "Premium", icon: "fa-birthday-cake", veg: true, desc: "Loaded with Kitkat" },
  { name: "Dark Forest", price: "25.99", unit: "/ lb", category: "cakes", tag: "Choco Treat", icon: "fa-birthday-cake", veg: true, desc: "Dark chocolate forest" },
  { name: "Red Velvet Cake", price: "25.99", unit: "/ lb", category: "cakes", tag: "House Special", icon: "fa-birthday-cake", veg: true, desc: "Iconic red velvet" },
  { name: "Creamy Vanilla Cake", price: "21.99", unit: "/ lb", category: "cakes", tag: "House Special", icon: "fa-birthday-cake", veg: true, desc: "Classic vanilla cream" },
  { name: "Biscoff Cheesecake", price: "25.99", unit: "/ lb", category: "cakes", tag: "House Special", icon: "fa-birthday-cake", veg: true, desc: "Biscoff cheesecake" },
  { name: "Gulab Jamun Cheesecake", price: "25.99", unit: "/ lb", category: "cakes", tag: "House Special", icon: "fa-birthday-cake", veg: true, desc: "Fusion gulab jamun cheesecake" },
  { name: "Mango Cheesecake", price: "25.99", unit: "/ lb", category: "cakes", tag: "House Special", icon: "fa-birthday-cake", veg: true, desc: "Mango cheesecake" },

  // ============ SNACKS ============
  { name: "Veg. Grill Sandwich", price: "9.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Grilled veggie sandwich (Jain/Swami available)" },
  { name: "Potato Stuffed Grill Sandwich", price: "9.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Spicy potato grill sandwich" },
  { name: "Paneer Tikka Sandwich", price: "9.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Tandoori paneer sandwich" },
  { name: "Grill Cheese Sandwich", price: "7.99", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Classic grilled cheese" },
  { name: "Bread Butter", price: "2.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Buttered fresh bread" },
  { name: "Chutney Sandwich", price: "3.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Mint chutney sandwich" },
  { name: "Spinach & Corn Sandwich", price: "9.49", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Creamy spinach corn" },
  { name: "Shezwan Paneer Roll", price: "8.99", category: "snacks", tag: "Sandwich", icon: "fa-bread-slice", veg: true, desc: "Spicy shezwan paneer roll" },
  { name: "Cheese Pizza", price: "12.49", category: "snacks", tag: "Pizza", icon: "fa-pizza-slice", veg: true, desc: "Mozzarella cheese pizza" },
  { name: "Veggie Pizza", price: "12.49", category: "snacks", tag: "Pizza", icon: "fa-pizza-slice", veg: true, desc: "Loaded veggie pizza (Jain/Swami)" },
  { name: "Pesto Paneer Pizza", price: "13.75", category: "snacks", tag: "Pizza", icon: "fa-pizza-slice", veg: true, desc: "Pesto paneer fusion pizza" },
  { name: "Paneer Tikka Pizza", price: "13.75", category: "snacks", tag: "Pizza", icon: "fa-pizza-slice", veg: true, desc: "Indian-style paneer tikka pizza" },
  { name: "Vada Pav", price: "7.99", category: "snacks", tag: "House Special", icon: "fa-burger", veg: true, desc: "Mumbai-style vada pav" },
  { name: "Cheese Vada Pav", price: "8.99", category: "snacks", tag: "House Special", icon: "fa-burger", veg: true, desc: "Vada pav with melted cheese" },
  { name: "Kutchi Dabeli", price: "8.99", category: "snacks", tag: "House Special", icon: "fa-burger", veg: true, desc: "Sweet & spicy Kutchi dabeli" },
  { name: "Veggie Burger", price: "8.99", category: "snacks", tag: "House Special", icon: "fa-burger", veg: true, desc: "Loaded veggie burger" },
  { name: "Chole Kulcha", price: "8.99", category: "snacks", tag: "House Special", icon: "fa-bowl-food", veg: true, desc: "Punjabi chole kulcha" },
  { name: "Chilly Cheese Toast", price: "7.99", category: "snacks", tag: "House Special", icon: "fa-bread-slice", veg: true, desc: "Spicy cheese toast" },
  { name: "Cheesy Garlic Bread", price: "7.99", category: "snacks", tag: "House Special", icon: "fa-bread-slice", veg: true, desc: "Loaded cheese garlic bread" },
  { name: "Jalapeno Poppers", price: "4.49", category: "snacks", tag: "Munching", icon: "fa-pepper-hot", veg: true, desc: "Cheese-stuffed jalapenos" },
  { name: "Mozzarella Sticks", price: "4.49", category: "snacks", tag: "Munching", icon: "fa-cheese", veg: true, desc: "Crispy mozzarella sticks" },
  { name: "Masala Fries", price: "5.49", category: "snacks", tag: "Munching", icon: "fa-french-fries", veg: true, desc: "Indian-spiced fries" },

  // ============ CAKE SHAKES ============
  { name: "Chocolate Chip Brownie Shake", price: "7.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Brownie blended shake (also $9.99 / 16oz)" },
  { name: "Walnut Brownie Shake", price: "8.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Walnut brownie shake (also $10.99 / 16oz)" },
  { name: "Rich Alphonso Shake", price: "6.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Premium alphonso mango (also $8.99 / 16oz)" },
  { name: "Strawberry Shake", price: "7.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Fresh strawberry shake (also $9.99 / 16oz)" },
  { name: "Oreo Shake", price: "8.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Oreo crunch shake (also $10.99 / 16oz)" },
  { name: "Pine Butterscotch Shake", price: "7.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Pineapple butterscotch (also $9.99 / 16oz)" },
  { name: "Ferrero Rocher Shake", price: "9.99", unit: "/ 12oz", category: "shakes", tag: "Premium", icon: "fa-mug-hot", veg: true, desc: "Premium Ferrero shake (also $11.99 / 16oz)" },
  { name: "Red Velvet Shake", price: "8.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Red velvet shake (also $10.99 / 16oz)" },
  { name: "Choco Latte Shake", price: "7.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Coffee chocolate shake (also $9.99 / 16oz)" },
  { name: "Nutty Rose Shake", price: "8.99", unit: "/ 12oz", category: "shakes", tag: "Cake Shake", icon: "fa-mug-hot", veg: true, desc: "Rose & nuts shake (also $10.99 / 16oz)" },

  // ============ PUFFS & TEA ============
  { name: "Masala Puff", price: "2.99", category: "puffs", tag: "Puff", icon: "fa-cookie", veg: true, desc: "Spicy potato masala puff" },
  { name: "Paneer Puff", price: "3.99", category: "puffs", tag: "Puff", icon: "fa-cookie", veg: true, desc: "Spiced paneer puff" },
  { name: "Veg. Cheese Puff", price: "3.99", category: "puffs", tag: "Puff", icon: "fa-cookie", veg: true, desc: "Veggie cheese puff" },
  { name: "Cheesy Corn Puff", price: "3.99", category: "puffs", tag: "Puff", icon: "fa-cookie", veg: true, desc: "Cheese & corn puff" },
  { name: "Ratlami Sev Samosa", price: "3.99", category: "puffs", tag: "Samosa", icon: "fa-cookie", veg: true, desc: "Spicy Ratlami sev samosa" },
  { name: "Jain Samosa", price: "4.49", category: "puffs", tag: "Samosa", icon: "fa-cookie", veg: true, desc: "Jain-style samosa" },
  { name: "Swaminarayan Samosa", price: "4.49", category: "puffs", tag: "Samosa", icon: "fa-cookie", veg: true, desc: "Swaminarayan samosa" },
  { name: "Chinese Samosa", price: "3.99", category: "puffs", tag: "Samosa", icon: "fa-cookie", veg: true, desc: "Chinese-style samosa" },
  { name: "Masala Tea", price: "1.99", category: "puffs", tag: "Beverage", icon: "fa-mug-hot", veg: true, desc: "Hot Indian masala chai" },
];
